language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-25.0.0
    # The SDK version used to compile your project
    - android-25
    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'
before_script:
    - chmod +x gradlew
script:
  - ./gradlew test
