language: android
android:
  components:
    # - platform-tools
    # - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
    - extra-android-m2repository
jdk:
  - oraclejdk8